### ISSUE TITLE
Background music

### ISSUE THREAD

**Issue by taitfuller** [Alxjlv/se206-ass3#100]
- [x] Choose music
- [x] Research audio overlaying
- [x] Implement optional background music playing

Requirement:
> They should also have the option to add background music to the creation, in addition to the synthesised text - 3rd October update

**Comment by taitfuller** [comment]
Nasser's announcement (10/10/2019):

> Dear developers, 
> 
> Given that you will have different projects, different target audiences, etc, then it makes sense that your pick tracks that work best for your project theme. 
> 
> However, you must follow the instructions below. This is a good exercise to practice software engineering professional and understand legality of digital content. Rather than giving you limited tracks, this gives you the freedom to legally use media:
> - Access tracks directly from here: http://ccmixter.org (Links to an external site.)
> - Read the Terms of Use (http://ccmixter.org/terms (Links to an external site.)), particularly Section 4.
> - Search for tracks you like, and do as follows:
>    - As an example, assume you pick this track:  http://ccmixter.org/files/grapes/16626 (Links to an external site.)
>    - All the tracks here fall under some variant of a Creative Commons (https://en.wikipedia.org/wiki/Creative_Commons (Links to an external site.)) license.
>    - Recognise that different tracks will fall under different licenses (but still a variant of Creative Commons license). As such, you should click on the top-right section which gives the link to the license (e.g. "Click here for how to give credit and other conditions"). That link gives a "human friendly version" of the license, but the full license can be found by clicking "This is a human-readable summary of (and not a substitute for) the license". 
>    - Skim over that license, and decide if it meets the suitability of your project use. 
>    - If so, you may use the track. In almost all cases, you will be required to attribute the track (http://ccmixter.org/how-to-attribute-ccmixter-tracks (Links to an external site.)). This includes the link to the track, name, author, and a link to the original license. You can attribute this in the >    - README file of your project for each track you use. 
>
> - Avoid having more than 5 tracks, and try to keep your tracks minimum in terms of file sizes (otherwise your project will get too large). If you really like a track but it's a large file (e.g. over a few MB), then you should trim it and include only the trimmed version (this is referred to "Adaption" or "Derivative Work" depending on the CC variant, and you still need to attribute the original).
> - Please keep in mind we have about 50 group submissions to download.. so please try to keep your submission under 20 MB if possible.
> - Remember to attribute the tracks as stated here: http://ccmixter.org/how-to-attribute-ccmixter-tracks (Links to an external site.)
>
> Cheers, 
> Nasser

**Comment by Alxjlv** [comment]
[link](https://stackoverflow.com/questions/14498539/how-to-overlay-downmix-two-audio-files-using-ffmpeg/14507851#14507851)
For merging two audio files with different volumes and different duration following command will work:

`ffmpeg -y -i audio1.mp3 -i audio2.mp3 -filter_complex "[0:0]volume=0.09[a];[1:0]volume=1.8[b];[a][b]amix=inputs=2:duration=longest" -c:a libmp3lame output.mp3`
Here duration can be change to longest or to shortest, you can also change the volume levels according to your need.

If you're looking to add background music to some voice use the following command as in the gaps the music will become loud automatically:

`ffmpeg -i bgmusic.mp3 -i audio.mp3 -filter_complex "[1:a]asplit=2[sc][mix];[0:a] sc]sidechaincompress=threshold=0.003:ratio=20[bg]; [bg][mix]amerge[final]" -map [final] final.mp3`

In this threshold is something whose value will decide how much loud the audio should be, the less the threshold more the audio will be. Ratio gives how much the other audio should be compressed, the more the ratio the more the compression is.
