### ISSUE TITLE
Review reminder system

### ISSUE THREAD

**Issue by Alxjlv** [Alxjlv/se206-ass3#102]
Target audience: Elderly. As such, we're assuming that they will know how to use the application and are pursuing memory retention rather than learning per say.

- [x] Sorting by least viewed
- [x] Sorting by least confident
- [x] "To review" sorting option
- [x] Default to "to review" sorting option on starting

**Comment by Alxjlv** [comment]
From project brief:
Review reminder system: The idea here is that after the learner creates a range of
creations, they get archived. Ultimately, they should be encouraged to review
them in order to reinforce their learning. The application will scaffold this review
process by keeping track of which items the user should prioritise in reviewing.
The priority order is based on a combination of (i) user confidence ratings (the
user gives a confidence rating for each creation, where lower-rated confidence
creations get higher priority for reviewing), and (ii) least-reviewed creations
(oldest-reviewed creations get highest priority). The user might decide to rank
priority by confidence first (and then oldest-reviewed), or rank priority by oldest reviewed first (and then confidence).

**Comment by taitfuller** [comment]
How should we define a view? Clicking on a creation in the list? Or fully/partially playing a creations video?
