### ISSUE TITLE
Java & fxml version - 8 or 11?

### ISSUE THREAD

**Issue by Alxjlv** [Alxjlv/se206-ass3#15]
I'm currently on java 8 & I built all the fxml scenes in scenebuilder 8. However, recent commits have changed the fxml version to 11

**Comment by taitfuller** [comment]
Oh no - just noticed I'm having the same problem 😂. It will have been from me modifying the .fxml files in Scenebuilder to specify ID's for nodes to integrate with the Model. Wasn't aware that Scenebuilder specified a version - is there a way for us to specify a downgrade?

**Comment by Alxjlv** [comment]
I think there's simply a line in the fxml that we can change to 8 instead of 11 - however I think you're using scenebuilder 11, and that'll automatically build java 11 fxml files. Scenebuilder 8 might be a viable option if you were willing to downgrade to it haha.

**Comment by taitfuller** [comment]
Ah that must be it! Can you open the files I've edited in Scenebuilder 11? If not, might need to branch from a prior commit where the files are version 8, edit the Scenes to include Controllers and id's, then merge into master

**Comment by Alxjlv** [comment]
It's fairly trivial to change the version - it's simply just a line within the fxml. I'll jump in and change them when I get onto image downloading a bit more
