### ISSUE TITLE
Creating Creations

### ISSUE THREAD

**Issue by taitfuller** [Alxjlv/se206-ass3#21]
Fully implement CreationBuilder.build() to create Creations

Tasks:

- [x] Implement CreationBuilder with CreationManager
- [x] Determine File Structure. See #20 
- [x] Download images. See #19 
- [x] Implementation for combining
- [x] FFMPEG calls - combine audio chunks, images and search term. Potentially use [this](https://github.com/bramp/ffmpeg-cli-wrapper) wrapper for FFMPEG - import into Gradle using [JitPack](https://jitpack.io)
    - [x] audio chunks combined
    - [x] duration of audio
    - [x] ffmpeg slideshow
    - [x] combine slideshow and audio
    - [x] search term overlay on slideshow
- [x] Progress updates. Ideally progress bar in Creations ListView

**Comment by taitfuller** [comment]
For combining images, the following approach could be used:

Create `input.txt` with the following:
```
file 'images/<id0>.jpg'
duration <time>
file 'images/<id1>.jpg'
duration <time>
file 'images/<id2>.jpg'
duration <time>
file 'images/<id2>.jpg'
```

> Note: The last image must have its file included twice

Then the following command may be run:

`ffmpeg -f concat -i input.txt -vsync vfr -pix_fmt yuv420p output.mp4 -v quiet -y`

**Comment by Alxjlv** [comment]
May want to scale images so they can be divisible by 2
width with height scaled: `-vf scale=500:-2` 
or 
height with width scaled:`-vf scale=-2:720`
found from [here](https://stackoverflow.com/questions/20847674/ffmpeg-libx264-height-not-divisible-by-2)

**Comment by Alxjlv** [comment]
comments for combining from past issue:
`sox file1.wav file2.wav output.wav`

**Comment by Alxjlv** [comment]
Creating slideshow - with the search term and with scaling
`ffmpeg -f concat -i input.txt -vf "scale=500:-2, drawtext=fontfile=Montserrat-Regular:fontsize=60:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2:text=\'"+searchTerm+"\'" -vsync vfr -pix_fmt yuv420p slideshow.avi -v quiet`

Scale AND text found from [here](https://superuser.com/questions/797190/ffmpeg-drawtext-on-top-of-scaled-video-regardless-of-image-size)

**Comment by Alxjlv** [comment]
Combining video and image:
`ffmpeg -i combined.wav -i slideshow.avi -c copy creation.avi -v quiet`

**Comment by Alxjlv** [comment]
Converting to mp4 from avi:
`ffmpeg -i creation.avi -c:v libx264 -crf 19 -preset slow -c:a libfdk_aac -b:a 192k -ac 2 creation.mp4 -v quiet`

Command found from [here](https://superuser.com/questions/525249/convert-avi-xvid-to-mp4-h-264-keeping-the-same-quality)

**Comment by Alxjlv** [comment]
First combine them with `ffmpeg -f concat -i input.txt -vf scale=500:-2 -vsync vfr -pix_fmt yuv420p slideshow.avi -v quiet`
Then add text and convert to mp4 `ffmpeg -i creation.avi -vf "drawtext=fontfile=Montserrat-Regular:fontsize=60:fontcolor=white:x=(w-text_w)/2:y=(h-text_h)/2:text=\'"+searchTerm+"\'" -c:v libx264 -crf 19 -preset slow -c:a libfdk_aac -b:a 192k -ac 2 creation.mp4 -v quiet`
