### ISSUE TITLE
Wikit Search

### ISSUE THREAD

**Issue by taitfuller** [Alxjlv/se206-ass3#22]
Implement Alex's Wikit Task from Assignment 2

**Comment by Alxjlv** [comment]
Existing wikit code is a good time-saving feature, and at this point, it seems like there is a lot of additional work to do so for now maybe implement wikit

**Comment by taitfuller** [comment]
Yeah I agree. If we've got time on the weekend can always implement the API instead

**Comment by taitfuller** [comment]
Your Wikit code from A2 sounds more optimised than mine - want to integrate that in?
