### ISSUE TITLE
Image previewing & selection

### ISSUE THREAD

**Issue by Alxjlv** [Alxjlv/se206-ass3#23]
We need to add image previewing in between snippets and naming
Requirements:
- [x] Extra page for previewing
- [x] In between chunkView & nameView
- [x] Lazy loading of 10 images when the wikipedia search is first pressed
- [x] Drag and drop to rearrange
- [x] Up/Down buttons
- [x] Delete image
- [x] Retain order
- [x] Figure out how many images to download - default to 10?

**Comment by taitfuller** [comment]
I'll put this down as a nice-to-have but should be once of the first nice-to-have's we implement
