### ISSUE TITLE
Creating Audio

### ISSUE THREAD

**Issue by Alxjlv** [Alxjlv/se206-ass3#27]
Similar to #21 and #11 - the audio creation process needs to be streamlined
- [x] Selecting voices
- [x] Festival config
- [x] espeak config
- [x] Implementation for festival
- [x] Implementation for espeak

**Comment by Alxjlv** [comment]
We can use sox to combine the audio files (in the wav format). The syntax is as follows:
`sox file1.wav file2.wav output.wav`

**Comment by Alxjlv** [comment]
Festival config as follows:
1. Create a .scm file for the voice (other settings can be added here, eg slower or faster)
1. Have the text for the chunk we want to voice
1. Use the command `text2wave -o result.wav text.txt -eval voicesettings.scm`

**Comment by Alxjlv** [comment]
For previewing without text2wave & festival
1. generate a .scm file with the voice in the format `(voice_kal_diphone)`
1. add the line `(SayText "String here")` underneath
1. use the command `festival -b your.scm`

**Comment by taitfuller** [comment]
Solved in #38
