### ISSUE TITLE
Flickr Integration

### ISSUE THREAD

**Issue by taitfuller** [Alxjlv/se206-ass3#3]
Requirements:
- [x] [Flicker4Java API](https://github.com/boncey/Flickr4Java) (via Nasser)
- [x] Allow user to choice how many images to use - no greater than 10
- [x] [API Key](https://www.flickr.com/services/api/)
- [x] Image downloading
- [x] How to store the downloaded images

**Comment by taitfuller** [comment]
Nasser's Announcement (on Canvas):

> FlickrExample: You will find this useful for Assignment 3. Most importantly, it includes all the libraries you need (inside the lib folder), as well as an example piece of code that will allow you to download and save images given a query to search. You should refer to the online documentations (https://github.com/boncey/Flickr4Java (Links to an external site.)) for the API and more information on what can be done, including how to request an API key to actually use the API. In the code for your assignments+project, it will be easier if you include this Key to make the marking easier. See the example flickr-api-keys.txt file in the project, this is where you need to enter your key etc.

Example is available via [ACP](https://acp.foe.auckland.ac.nz/ide)

**Comment by taitfuller** [comment]
[Flickr API Reference](https://www.flickr.com/services/api/)

**Comment by Alxjlv** [comment]
Currently have API calls working & images downloading correctly - images need to be stored in the correct place though. We'll need to iron out how this can be integrated as this likely would be involved in the creation process - and the API calls/downloading can take a significant amount of time and will need to be integrated into the threading of the creation process (it is also currently multithreaded)

**Comment by taitfuller** [comment]
Awesome stuff man! I'd say the best place for the API calls would be inside CreationBuilder.build(). If it's going to take considerable time I'll definitely try put together some form of Progress display in the Creation ListView

**Comment by Alxjlv** [comment]
Seems like now a good place to put the API calls would be within the search function to lazy load the images
